Algoritmo "Antecessor"
// Disciplina : Lógica de Programação
// Professor  : Jailson Costa dos Santos
// Descrição  : Solicita um números e mostra seu antecessor
// Autor(a)   :  Lucas Moreira
// Data atual : 05/04/2026
Var
// Seção de Declarações das variáveis
num1,antecessor: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
Escreva("Digite um número:")
Leia(num1)
antecessor<- num1 - 1
Escreva("O antecessor de",num1, " é:",antecessor)
Fimalgoritmo