Algoritmo "Dimensões_retangulo"
//  
//  
// Disciplina : Lógica de Programação
// Professor  : Jailson Costa dos Santos
// Descrição  : Solicita a base e a altura e mostra qual a área de um retangulo.
// Autor(a)   :  Lucas Moreira
// Data atual : 06/04/2026
Var
// Seção de Declarações das variáveis
base,altura,area:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
Escreva("Digite a altura do retangulo:")
Leia(altura)
Escreva("Digite a base do retangulo:")
Leia(base)
area<- altura * base
Escreva("A área do retangulo é de::",area)
Fimalgoritmo