Algoritmo "Dimensões_triangulo"
// Disciplina : Lógica de Programação
// Professor  : Jailson Costa dos Santos
// Descrição  : Solicita a base a e altura de um triangulo e mostra sua area.
// Autor(a)   :  Lucas Moreira
// Data atual : 06/04/2026
Var
// Seção de Declarações das variáveis
altura,base,area:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
Escreva("Digite a base do triangulo:")
Leia(base)
Escreva("Digite a altura do triangulo:")
Leia(altura)
area <- (base * altura) / 2
Escreva("A area do triangulo é de:",area)
Fimalgoritmo