Algoritmo "Dimensões_quadrado"
// Disciplina : Lógica de Programação
// Professor  : Jailson Costa dos Santos
// Descrição  : Solicita o lado do quadradro e retorna sua área.
// Autor(a)   :  Lucas Moreira
// Data atual : 05/04/2026
Var
// Seção de Declarações das variáveis
area,lado:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
Escreva("Digite o lado do quadrado:")
Leia(lado)
area <- lado * lado
Escreva("A area do quadrado é de:",area)
Fimalgoritmo