Algoritmo "Dimensões_circulo"

// Disciplina : Lógica de Programação
// Professor  : Jailson Costa dos Santos
// Descrição  : Solicita o raio do circulo e mostra sua área.
// Autor(a)   :  Lucas Moreira
// Data atual : 05/04/2026
Var
// Seção de Declarações das variáveis
raio,area:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
Escreva("Digite o raio do circulo:")
Leia(raio)
area <- 3.14 *(raio * raio)
Escreva("A área do circulo é de::",area)
Fimalgoritmo