Algoritmo "Subtração"
// Disciplina : Lógica de Programação
// Professor  : Jailson Costa dos Santos
// Descrição  : Solicita dois números e realiza a subtração
// Autor(a)   :  Lucas Moreira
// Data atual : 08/04/2026
Var
// Seção de Declarações das variáveis
num1, num2, subtracao: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
Escreva("Digite um número:")
Leia(num1)
Escreva("Digite um número:")
Leia(num2)
subtracao<- num1 - num2
Escreva("A subtração dos números digitados é:",subtracao)
Fimalgoritmo