Algoritmo "Sucessor"
// Disciplina : Lógica de Programação
// Professor  : Jailson Costa dos Santos
// Descrição  : Solicita um número e mostra seu sucessor
// Autor(a)   :  Lucas Moreira
// Data atual : 08/04/2026
Var
// Seção de Declarações das variáveis
num1,sucessor: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
Escreva("Digite um número:")
Leia(num1)
sucessor<- num1 + 1
Escreva("O sucessor de",num1," é:",sucessor)
Fimalgoritmo